const	FRAME_RATE			= 30;

const	CANVAS_WIDTH		= 800;
const	CANVAS_HEIGHT		= 600;

const	GRID_WIDTH			= CANVAS_WIDTH / 10;
const	GRID_HEIGHT			= CANVAS_HEIGHT / 10;

const	CELL_LENGTH			= 10;

const	BACKGROUND_COLOR	= "#AACCFF";
const	CELLS_COLOR 		= 0;
const	TXT_STEP_COLOR		= "#D72323";
