const	CANVAS_WIDTH		= 800;
const	CANVAS_HEIGHT		= 600;

const	CELL_LENGTH			= 10;

const	GRID_WIDTH			= CANVAS_WIDTH / CELL_LENGTH;
const	GRID_HEIGHT			= CANVAS_HEIGHT / CELL_LENGTH;

const	BACKGROUND_COLOR	= "#AACCFF";
const	CELLS_COLOR 		= 0;
const	TXT_STEP_COLOR		= "#D72323";
